 -> program
program -> expression_list
expression_list -> expression_list expression
expression_list -> expression
expression -> assignment SEMICOLON
expression -> assignment COMMA
expression -> assignment
assignment -> expression ASS_IGN mapping
assignment -> expression ASS_ADD mapping
assignment -> expression ASS_SUB mapping
assignment -> expression ASS_MUL mapping
assignment -> expression ASS_DIV mapping
assignment -> expression ASS_SHL mapping
assignment -> expression ASS_SHR mapping
assignment -> mapping
mapping -> mapping COLON bit_shift
mapping -> bit_shift
bit_shift -> bit_shift BIT_LEFT spaceship
bit_shift -> bit_shift BIT_RIGHT spaceship
bit_shift -> spaceship
spaceship -> spaceship CMP_IE comparison
spaceship -> comparison
comparison -> comparison CMP_LT equality
comparison -> comparison CMP_GT equality
comparison -> comparison CMP_LE equality
comparison -> comparison CMP_GE equality
comparison -> equality
equality -> equality CMP_EQ bit_and
equality -> equality CMP_NE bit_and
equality -> bit_and
bit_and -> bit_and BIT_AND bit_xor
bit_and -> bit_xor
bit_xor -> bit_xor BIT_XOR bit_or
bit_xor -> bit_or
bit_or -> bit_or BIT_OR log_and
bit_or -> log_and
log_and -> log_and LOG_AND log_or
log_and -> log_or
log_or -> log_or LOG_OR sum
log_or -> sum
sum -> sum MATH_ADD product
sum -> sum MATH_SUB product
sum -> product
product -> product MATH_MUL base_expression
product -> product MATH_DIV base_expression
product -> product MATH_MOD base_expression
product -> base_expression
paren_block -> OP expression_list CP
paren_block -> OP CP
brace_block -> OB expression_list CB
brace_block -> OB CB
curly_block -> OC expression_list CC
curly_block -> OC CC
base_expression -> IF
base_expression -> ELSE
base_expression -> FOR
base_expression -> IN
base_expression -> WHILE
base_expression -> STRUCT
base_expression -> RETURN
base_expression -> IDENTIFIER
base_expression -> LIT_S8
base_expression -> LIT_S16
base_expression -> LIT_S32
base_expression -> LIT_C8
base_expression -> LIT_C16
base_expression -> LIT_C32
base_expression -> LIT_I8
base_expression -> LIT_I16
base_expression -> LIT_I32
base_expression -> LIT_I64
base_expression -> LIT_U8
base_expression -> LIT_U16
base_expression -> LIT_U32
base_expression -> LIT_U64
base_expression -> LIT_F32
base_expression -> LIT_F64
base_expression -> BIT_AND base_expression
base_expression -> MATH_ADD base_expression
base_expression -> MATH_SUB base_expression
base_expression -> MATH_MUL base_expression
base_expression -> INC base_expression
base_expression -> DEC base_expression
base_expression -> base_expression INC
base_expression -> base_expression DEC
base_expression -> base_expression DOT IDENTIFIER
base_expression -> base_expression DOUBLECOLON IDENTIFIER
base_expression -> base_expression paren_block
base_expression -> base_expression brace_block
base_expression -> base_expression curly_block
base_expression -> OP expression CP
